language: python
python:
 - "3.8"
services:
 - docker
before_install:
 - pip install --upgrade --no-cache-dir --default-timeout=210 skencli
script:
 - docker run --rm --mount type=bind,source="$(pwd)",target=/scan dops-registry.fortinet-us.com/fortidevsecops/fdevsec_sec_engine:0.0.1 main
